import BlogCard from "@/components/BlogCard";
import SearchForm from "@/components/SearchForm";
import { Post } from "@/types";

const page = async ({
  searchParams,
}: {
  searchParams: Promise<{ query: string }>;
}) => {
  const { query } = await searchParams;

  const res = await fetch(
    `${process.env.NEXT_PUBLIC_URL_ENDPOINT}/api/v1/post${
      query ? `?query=${query}` : ""
    }`
  );

  const posts: Post[] = await res.json();

  const reversedPosts = posts.length ? posts.reverse() : [];

  return (
    <>
      <section>
        <h1 className="text-4xl font-semibold">Community Showcase</h1>

        <p className="text-gray-600 my-10">
          Browse through a collection of stunning images generated by the
          community
        </p>

        <SearchForm />
      </section>

      {reversedPosts.length ? (
        <section className="mt-10 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
          <BlogCard {...reversedPosts[0]} style="col-span-2 row-span-2" />

          {reversedPosts.slice(1).map((post, index) => (
            <BlogCard key={index} {...post} style="col-span-1" />
          ))}
        </section>
      ) : (
        <p className="text-gray-800 text-xl text-center mt-16">
          No posts found
        </p>
      )}
    </>
  );
};

export default page;
