export const prompts = [
  "A futuristic city skyline at sunset, cyberpunk style",
  "A serene forest with mystical glowing mushrooms",
  "Portrait of a medieval knight in shining armor",
  "A dragon flying over snow-capped mountains",
  "A cozy cottage in a snowy winter landscape",
  "A steampunk airship floating in the clouds",
  "A close-up of a tiger's face in ultra-realistic style",
  "An underwater coral reef teeming with colorful fish",
  "A magical library with floating books",
  "A desert landscape with a giant crystal formation",
  "A space station orbiting a distant planet",
  "A robot artist painting in a studio",
  "A fantasy castle on a floating island",
  "A glowing neon street market at night",
  "A giant octopus attacking a pirate ship",
  "A surreal dreamscape with melting clocks",
  "A cybernetic samurai in a neon city",
  "A peaceful Japanese garden with cherry blossoms",
  "A futuristic sports car racing on a neon track",
  "A portrait of an alien queen with bioluminescent skin",
  "A medieval village during a festival",
  "A mystical waterfall surrounded by enchanted plants",
  "A giant treehouse village in a jungle",
  "A space battle between starships",
  "A surreal city with upside-down buildings",
  "A portrait of a wizard casting a spell",
  "A sunset over a tranquil ocean with islands",
  "A futuristic robot butler serving tea",
  "A steampunk clock tower in a busy city",
  "A forest inhabited by glowing spirits",
  "A portrait of a Viking warrior with a braided beard",
  "A fantasy marketplace with mythical creatures",
  "A dragon curled around a treasure hoard",
  "A cyberpunk hacker in a dark alley",
  "A giant mechanical spider in a cityscape",
  "A whimsical fairy village in the forest",
  "A mystical portal in a desert landscape",
  "A realistic portrait of a lion wearing a crown",
  "A spaceship landing on an alien planet",
  "A futuristic skyscraper covered in greenery",
  "A samurai standing under a red maple tree",
  "A fantasy creature blending features of lion and eagle",
  "A haunted mansion at night with glowing windows",
  "A surreal landscape with floating islands",
  "A medieval blacksmith forging a glowing sword",
  "A magical forest river with crystal clear water",
  "A cyberpunk neon-lit motorcycle chase",
  "A giant wave with glowing bioluminescent water",
  "A dragon perched on top of a volcano",
  "A mystical cave with glowing crystals",
  "A steampunk inventor in a cluttered workshop",
  "A portrait of a queen in renaissance style",
  "A futuristic city with flying cars and holograms",
  "A surreal desert with giant floating spheres",
  "A cyberpunk street scene with rain and neon lights",
  "A magical library inside a giant tree",
  "A warrior princess on horseback in a battlefield",
  "A glowing crystal floating above a mountain",
  "A fantasy tavern filled with adventurers",
  "A futuristic robot companion in a city park",
  "A giant sea monster emerging from the ocean",
  "A snowy mountain village with warm lights",
  "A mystical garden with glowing flowers at night",
  "A cyberpunk hacker surrounded by holographic screens",
  "A portrait of a majestic phoenix rising from flames",
  "A steampunk train traveling through mountains",
  "A dragon sleeping in a sunlit valley",
  "A fantasy airship floating among clouds",
  "A neon-lit alleyway in a futuristic city",
  "A magical forest with floating lanterns",
  "A realistic portrait of a wolf in the moonlight",
  "A spaceship flying through a colorful nebula",
  "A mystical castle on a cliff by the ocean",
  "A fantasy marketplace with magical artifacts",
  "A cybernetic soldier in a futuristic battlefield",
  "A whimsical fairy riding a butterfly",
  "A steampunk robot serving drinks in a tavern",
  "A dragon and knight facing off on a cliff",
  "A glowing underwater city inhabited by mermaids",
  "A futuristic city with monorails and flying cars",
  "A surreal landscape with giant floating rocks",
  "A magical forest with talking animals",
  "A medieval king in a golden throne room",
  "A portrait of a space explorer on a distant planet",
  "A steampunk airship battle in the clouds",
  "A mystical mountain with floating temples",
  "A neon futuristic market filled with robots",
  "A dragon flying through a stormy sky",
  "A whimsical cottage with a giant garden",
  "A cyberpunk city skyline at night with neon lights",
  "A magical waterfall with glowing fish",
  "A portrait of an elf warrior with a bow",
  "A surreal city with rivers flowing in the sky",
  "A steampunk inventor testing a flying machine",
  "A fantasy knight standing before a dragon",
  "A mystical crystal cave glowing with colors",
  "A futuristic robot exploring a jungle",
  "A snowy landscape with northern lights",
  "A neon futuristic race track with flying cars",
  "A dragon perched on a cliff under a full moon",
  "A magical floating island with waterfalls",
  "A portrait of a cyberpunk hacker girl",
  "A steampunk city with mechanical airships",
  "A fantasy tavern full of adventurers",
  "A glowing tree in a dark mystical forest",
  "A futuristic city under a giant dome",
  "A surreal desert with enormous glowing flowers",
  "A dragon and phoenix in an epic battle",
  "A magical library with endless shelves of books",
  "A cyberpunk street scene with neon signs and rain",
  "A whimsical village on top of giant mushrooms",
  "A portrait of a wizard with glowing runes",
  "A futuristic city with vertical gardens",
  "A mystical waterfall surrounded by glowing stones",
  "A dragon guarding an ancient temple",
  "A fantasy castle floating in the clouds",
  "A steampunk city with gear-filled streets",
  "A glowing bioluminescent forest at night",
  "A cyberpunk alleyway with holographic graffiti",
  "A surreal mountain landscape with floating peaks",
  "A magical creature blending fox and bird features",
];
